#![allow(bad_style)]

use super::*;

// NOTE: The code generated by the idl code generator expects the types from
// nsstring to be in scope.
use nsstring::{nsACString, nsAString, nsCString, nsString};

// NOTE: The idl file nsrootidl.idl defines the type nsresult. As the type is
// defined to be the same type as nserror's type, we just import the only error
// definition we care about.
use nserror::NS_OK;

// NOTE: This file contains a series of `include!()` invocations, defining all
// idl interfaces directly within this module.
include!(concat!(env!("MOZ_TOPOBJDIR"), "/dist/xpcrs/all.rs"));
